### ISSUE TITLE
JSON left over from testing?

### ISSUE THREAD

**Issue by MattElcock** [ONSdigital/eq-extract-questions#3]
https://github.com/ONSdigital/eq-extract-questions/blob/ba47cf1bdeec5cb113890527f1e65258c23ba0bc/2_0001.json#

Usually, we wouldn't leave JSON in the repository like this unless it's in a subdirectory, called `data` (Runner is a good example of this)

It's just so the codebase is kept nice and tidy.

**Comment by martyncolmer** [comment]
renamed file
