### ISSUE TITLE
Port will conflict with Author -- consider changing this to something else

### ISSUE THREAD

**Issue by MattElcock** [ONSdigital/eq-extract-questions#4]
https://github.com/ONSdigital/eq-extract-questions/blob/ba47cf1bdeec5cb113890527f1e65258c23ba0bc/server.js#L34

In the (very very rare) circumstance that we'll fire up Author alongisde this app locally, either this or Author will complain as the port will be unavailable. Might want to change the port or make it so that we can change the port via an environment variable and have it default to something if it's left unset.

To my knowledge, here are all the ports that are being used by other services and might throw a wobbly if they're used:

- 3000; Author Front End
- 9000; Publisher (V2 and V3)
- 8000; Go Launcher (V2 and V3)
- 8080; Survey Register
- 4000; Author API
- 5000; Runner (V2 and V3)
- 8070; API Firestore Database
- 6379; API Redis

Unsure on which of these will actually complain, but probably best to steer away from them just incase.

**Comment by martyncolmer** [comment]
Docker-compose is using 3050 to avoid conflict. When deployed it will map to port 80 on an external ip.
